version: '3'
services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8000"
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true
    restart: always
