name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - deploy-doc  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs and Material theme
        run: |
          pip install mkdocs-material && pip install --upgrade pymdown-extensions python-markdown-math

      - name: Build the MkDocs site
        run: mkdocs build --clean
      
      - name: Add CNAME for custom domain
        run: echo 'docs.seatstand.com' > ./site/CNAME 

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Ensure you're using the latest version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
